export enum UserRole {
  Student = "Student",
  NonTechnicalPro = "Non-technical professional",
  TechnicalPro = "Technical professional",
  Founder = "Founder / Builder",
  Creator = "Creator / Marketer"
}

export enum UserGoal {
  Productivity = "Productivity",
  CareerGrowth = "Career growth",
  Fundamentals = "Learning AI fundamentals",
  Building = "Building products",
  Content = "Content creation",
  Automation = "Automation"
}

export enum AIFamiliarity {
  Beginner = "Beginner",
  Familiar = "Familiar",
  Regular = "Regular user",
  Advanced = "Advanced"
}

export enum LearningStyle {
  Practical = "Short & practical",
  StepByStep = "Step-by-step",
  Conceptual = "Concept → example",
  HandsOn = "Hands-on challenges"
}

export interface UserContext {
  id?: string; // Supabase ID
  name: string; // User's name
  role: UserRole;
  goals: UserGoal[];
  aiLevel: AIFamiliarity;
  learningStyle: LearningStyle;
  difficultyCeiling: number; // 1-5
  onboardingComplete: boolean;
}

// Agent 1: Raw Signal
export interface RawUpdateSignal {
  sourceId: string;
  rawContent: string;
  detectedAt: string;
  url?: string;
}

export enum UpdateType {
  Capability = "New Capability",
  LimitChange = "Limit Change",
  WorkflowShift = "Workflow Shift",
  Fix = "Fix / Deprecation"
}

// Agent 2: Verified Update
export interface VerifiedUpdate {
  id: string;
  title: string;
  shortSummary: string; // Max 120 chars
  updateType: UpdateType;
  difficultyLevel: number; // 1-5
  relevanceScore: number; // 0-100
  lessonEligible: boolean;
  source: string;
  date: string;
  url?: string;
}

// Agent 3: Micro Lesson
export interface MicroLesson {
  id: string;
  updateId: string; // Can be update ID or tool ID
  title: string;
  duration: string; // e.g. "5 min"
  whyItMatters: string;
  whatChanged: string; // Or "What this tool does"
  steps: string[];
  mentalModel: string;
  practiceTask: string;
  visualConcept?: string; // Description for the image generator
  imageUrl?: string; // Generated by NanoBanana Pro
}

// Agent 4: Tool Suggestion
export interface ToolSuggestion {
  id: string;
  name: string;
  category: string; // e.g. "Coding", "Writing", "Image"
  collection: "Major" | "New" | "Underrated"; // For sections
  description: string;
  useCases: string[]; // Detailed list of use cases
  bestFor: string[];
  matchScore: number;
  learningCurve: "Low" | "Medium" | "High";
  deltaAnalysis: string; // Renamed from geminiAnalysis
  trending: boolean; 
  url?: string;
}

// New Agent: Daily Life Integration
export interface DailyLifeHack {
  id: string;
  title: string; // e.g. "Automate Morning Emails"
  toolName: string;
  context: string; // "When you start your day..."
  action: string; // "Use this prompt..."
  impact: string; // "Saves 15 mins"
}

// New Feature: Master Model Guide
export interface ModelGuide {
  id: string;
  modelName: string; // e.g. "Claude 3.5 Sonnet"
  tagline: string;
  bestUseCases: string[];
  hiddenFeatures: string[];
  promptTemplates: string[]; // 2-3 copy-paste templates
  weaknesses: string;
  updatedAt: string;
  visualConcept: string; // Text description for the image generator
  imageUrl?: string; // Base64 data URI or URL
}

export interface UserStats {
  streak: number;
  lessonsCompleted: number;
  lastVisit: string;
  xp: number;
  level: number;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}